name: Build OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone OpenWrt
        run: |
          git clone --depth=1 --branch v25.12.5 https://github.com/openwrt/openwrt.git

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure
        run: |
          cd openwrt

          cat > .config <<EOF
          CONFIG_TARGET_ath79=y
          CONFIG_TARGET_ath79_generic=y
          CONFIG_TARGET_ath79_generic_DEVICE_tplink_tl-wdr4300-v1=y
          EOF

          make defconfig

      - name: Build
        run: |
          cd openwrt
          make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: openwrt/bin/targets/ath79/generic/*
